spring:
  application:
    name: firebase
  datasource:
    url: jdbc:mysql://localhost:3306/nutridiary
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: true
logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE
        orm:
          jpa:
            JpaTransactionManager: DEBUG
firebase:
  credential:
    resource-path: firebase.json