spring:
  application:
    name: firebase
  datasource:
    url: jdbc:h2:tcp://localhost/~/firetest
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: true
logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE
        orm:
          jpa:
            JpaTransactionManager: DEBUG
firebase:
  credential:
    resource-path: firebase.json